### PR TITLE
add turbolinks back to gemfile, add conditional for disabling it

### LINKED ISSUE #789: Files selected from BrowseEverything are not being reported on the input form
Files selected through BrowseEverything used to be reported on the input form by number of files selected, alerting the submitter that something had happened.  This message no longer appearsl

### PR DESCRIPTION
**Pull request by lawhorkl**
closes #789 

should be reviewed with uclibs/curate#85

### CODE REVIEW

**Comment by scherztc** [comment]
1. Left a byebug in your Gemfile.
2.  What about the Attach a File page?  Browse_Everything is in use there too.

**Comment by lawhorkl** [comment]
@scherztc yes, it works on the attach a file page as well... Probably should have clarified that. I'll remove the byebug and clarify the commit.

**Comment by lawhorkl** [comment]
The commit message was edited to be more clear and the byebug is removed.

**Comment by hortongn** [comment]
@scherztc @lawhorkl When I run this branch in the app it breaks the Browse Everything "Click here to upload remote files" button for me.  Clicking the button does nothing.  If I switch back to the *develop* branch the button works fine.  So TurboLinks is somehow related.

@scherztc, I think this is why the browse everything button is broken in the Curate test app too.

**Comment by lawhorkl** [comment]
just fixed merge conflicts

**Comment by lawhorkl** [comment]
just fixed issues with the curate branch - this one really does not like me!

**Pull request merged**
