### PR TITLE
Add bamboo files for analytics

### LINKED ISSUE #1065: Production: Integrate Google Analytics
Same as in Scholar 2

### PR DESCRIPTION
**Pull request by flutterflies**
fixes #1065 

Adds a bamboo file from configuring google analytics and update the hyrax config to enable analytics

Changes proposed in this pull request:
* Add bamboo file to set google analytics config options
* Change config options in `hyrax.rb.bamboo` to enable analytics

### CODE REVIEW

**Comment by flutterflies** [comment]
Before this gets merged we should make sure to create the cron job on the server and add these new variables to bamboo

**Comment by hortongn** [comment]
@flutterflies Can we also use a Bamboo variable for the `config.google_analytics_id`?  I worry that if we hard-code the tracker ID, anyone who clones the repo and runs Scholar would be using our real ID and might skew our statistics.

Can you post the rake task we need to schedule in cron?

**Comment by flutterflies** [comment]
Added a bamboo variable for `config.google_analytics_id`

the cron job will need to run `rake hyrax:stats:user_stats`

**Comment by hortongn** [comment]
@flutterflies Just noticed one other change.  Instead of creating a new config/analytics.yml.bamboo file, just put the bamboo variables into the existing config/analytics.yml file.  Sometimes we do need separate .bamboo and .sample files, but in this case I think we can just put the variables in the existing config/analytics.yml.

**Pull request merged**
