### PR TITLE
add seed data for testing on qa

### LINKED ISSUE #353: Create a set of "clean" data that can be loaded into the QA environment
Includes different types of works and different types of users

Eventually extend this to an automated process

### PR DESCRIPTION
**Pull request by crowesn**
Resolves #353

### CODE REVIEW

**Comment by crowesn** [comment]
bundle exec rake db:seed

**Comment by hortongn** [comment]
@crowesn This works perfectly except that it breaks if a user with one of those email addresses already exists in the database.  I think you want a conditional statement inside your accounts.each loop that first checks if a user with that email address already exists.  If so, just skip creating that account.  That way your rake task will work even if the accounts haven't been wiped beforehand.

**Comment by hortongn** [comment]
Something like 

        accounts.each do | email, name |
            unless User.where(email: email).exists?
                SeedMethods.new_account(email, name, rando_pass)
                system("echo #{email}, #{rando_pass} | mail -s 'new test account on qa' scholar@ucmail.uc.edu")
            end
        end

**Comment by crowesn** [comment]
This should be ready to go.

**Pull request merged**
