### PR TITLE
Configure UV and RIIF for Sufia.

### LINKED ISSUE #898: IIIF display of images
When the file is an image type, display the image with OpenSeadragon.

This will require a redesign of the work show page to make room for the viewer.

### PR DESCRIPTION
**Pull request by scherztc**
Fixes #898

Summary:

Use the Universal Image Viewer and RIIIF to give the works a zoom and pan option for attached image files.

### CODE REVIEW

**Comment by scherztc** [comment]
It is still doing the inconsistent load behavior on the first load.  After refresh, the viewer displays properly.

**Comment by scherztc** [comment]
It doesn't render the <iframe> tag.

**Comment by scherztc** [comment]
<iframe name="easyXDM_default6297_provider" id="easyXDM_default6297_provider" scrolling="no" src="http://localhost:3001/bower_includes/universalviewer/dist/uv-1.7.11/app.html?isHomeDomain=true&amp;isOnlyInstance=true&amp;manifestUri=%2Fconcern%2Fimages%2Frj430489x%2Fmanifest&amp;embedScriptUri=http://localhost:3001/bower_includes/universalviewer/dist/uv-1.7.11/lib/embed.js&amp;embedDomain=localhost&amp;domain=localhost&amp;isLightbox=false&amp;locale=en-GB&amp;xdm_e=http%3A%2F%2Flocalhost%3A3001%2Fconcern%2Fimages%2Frj430489x&amp;xdm_c=default6297&amp;xdm_p=4" frameborder="0" style="width: 100%; height: 400px;"></iframe>

**Comment by scherztc** [comment]
Fixed final issue by disabling turbolinks on the base/show.html.erb page.

**Comment by 13miciunasl** [comment]
This migration file needs to be removed

https://github.com/uclibs/scholar_uc/blob/feature/%23898_Rebase/db/migrate/20170317195058_add_allows_access_grant_to_workflow.curation_concerns.rb

**Comment by 13miciunasl** [comment]
Trying to edit an image file results in this error

scholar_dev/app/views/curation_concerns/file_sets/media_display/_image.html.erb where line #5 raised
undefined method `human_readable_type' for nil:NilClass

<% if @presenter.human_readable_type == 'File' %>

**Comment by scherztc** [comment]
@13miciunasl I updated the view to handle all conditions.

**Pull request merged**
