### PR TITLE
Set field display in catalog index view

### LINKED ISSUE #1179: Set catalog display of works to only show certain fields.
### Descriptive summary

I want to have consistent metadata labels in the catalog views of works and collections.

### Expected behavior

When the metadata profile was migrated to Scholar 3, I overly included too may fields on the catalog display of works.  This needs to trimmed down to the same fields displayed in Scholar 2.x

### PR DESCRIPTION
**Pull request by crowesn**
Fixes #1179 

Set catalog index to show only :title, :creator, and :description for for titles and collections.

Changes proposed in this pull request:
* Override default fields
* Update specs

### CODE REVIEW

**Comment by hortongn** [comment]
@crowesn The catalog index view always shows "Description" and "Creator" labels even when a work uses alternative fields like abstract or author.  The labels on the index page should match the labels we're using on each type of work.

**Comment by scherztc** [comment]
I know it would slow it down, but we might need some sort of logic method on the label element of:

''' ruby
config.add_index_field solr_name("creator", :stored_searchable), label: "Creator", itemprop: 'creator', link_to_search: solr_name("creator", :facetable)

config.add_index_field solr_name("description", :stored_searchable), label: "Description", itemprop: 'description', helper_method: :iconify_auto_link
''' 
The logic method would confirm work type before presenting labels value from locale.

'''ruby

      if work == Etd
        fill_in('Abstract', with: 'This is an abstract.')
        fill_in('Creator', with: 'Test User')
      elsif work == StudentWork
        fill_in('Description', with: 'This is an abstract.')
        fill_in('Creator', with: 'Test User')
      elsif work == Article
        fill_in('Abstract', with: 'This is an abstract.')
        fill_in('Author', with: 'Test User')
      else
        fill_in('Description', with: 'This is a description.')
        fill_in('Creator', with: 'Test User')
      end

'''

**Comment by crowesn** [comment]
Are these labels not part of the metadata profile?

**Comment by scherztc** [comment]
The catalog controller choices these labels based on the solr_field.  

Author and Abstract do not have their own metadata field.  The simple form applies a different label for the Creator and Description field, based on the value in the locale file for that work type.

See https://github.com/uclibs/scholar_uc/blob/develop/config/locales/article.en.yml

**Pull request merged**
