### PR TITLE
ETD work form changes

### LINKED ISSUE #1314: Adjust Metadata and behavior on ETD input form
### Descriptive summary

On ETD individual work input form, to be consistent with Scholar 2.x and metadata decisions, some adjustments are needed:

* Publisher default text should be "University of Cincinnati"

* Publisher help text should be "Enter the publisher associated with the ETD, typically the University of Cincinnati."

* Publisher is not repeatable.    (Repeatable on all other work types.)
 
* College should not have any default text associated with submitter's identity information, but does use the same drop-down list.

* Degree Program should not have any default text associated with submitter's department information.

(An ETD administrator, not the author, will submit ETDs, thus the reason not to associate default text in College and Degree Program with the submitter.)

* Degree Program help note should say "Enter the degree program associated with the ETD."

* Change Degree to not be repeatable.
   
* Type (genre) does not exist on ETD form in Scholar 2.x.  Confirm with Metadata SME that it is needed in 3.x.  If not needed, remove from metadata spreadsheet as well as code for ETD input form.  If needed, change help information to not refer to a Select option - since this is free text.  Suggested: "Enter a type matching your work.  Examples: Document, Article, Dataset, Image, Video, Other"
       
* Change label of geo_subject to "Geographic Subject" per other work types.   Add help notes and examples to be the same help and example text as on other work types.

* On entry for Committee Member on metadata spreadsheet, add applicable information to columns for RDF Mapping, Solrized, Gem.

### PR DESCRIPTION
**Pull request by crowesn**
Fixes #1314 

Changes proposed in this pull request:
* Add new :etd_publisher field for single-value publisher.
* Add form view override with class to hook script.
* Adapt creator auto populate script to exclude ETDs
* Add various label and help view tweaks

### CODE REVIEW

**Comment by hortongn** [comment]
@crowesn Please rebase your branch on develop and push up again.  We had to update solr_wrapper to fix a problem with Travis being able to download solr.

**Comment by newmanld** [comment]
See comment I added to #1314 re help text and other in Type field.

**Comment by crowesn** [comment]
This is done.



On Apr 28, 2017, at 11:13 AM, Glen Horton <notifications@github.com<mailto:notifications@github.com>> wrote:


@crowesn<https://github.com/crowesn> Please rebase your branch on develop and push up again. We had to update solr_wrapper to fix a problem with Travis being able to download solr.

**Comment by hortongn** [comment]
@crowesn A few changes are needed:

* Geographic Location should be Geographic Subject
* The default publisher field should default to "University of Cincinnati" only for a new work.  Don't force it for work edit.
* There are a couple of file conflicts that need resolved.

**Comment by newmanld** [comment]
@crowesn to add to @hortongn's comment above, see also #1314.

**Pull request merged**
