### PR TITLE
Configuration updates for Browse Everything (Kaltura and Dropbox).

### LINKED ISSUE #594: Video Work Type:  Integrate deposit from Kaltura into Scholar

### PR DESCRIPTION
**Pull request by scherztc**
Closes #594

### CODE REVIEW

**Comment by scherztc** [comment]
Close #957

**Comment by jamesvanmil** [comment]
Testing locally and I got the following error within Browse Everything:

screen shot 2016-10-20 at 2 52 49 pm

**Comment by scherztc** [comment]
There are two locations that you need to add the partner_id and administrator_secret_key.  

1.  config/browse_everything.yml
1.  config/initializers/kaltura.rb

**Comment by jamesvanmil** [comment]
Yeah - I set those with the secrets that you sent. I think is is related to my not having a Kaltura account for the driver to link to.

**Comment by scherztc** [comment]
Can you try logging into scholar-dev.uc.edu and share the error message?

**Comment by jamesvanmil** [comment]
Same error:

```
NoMethodError in BrowseEverything#show
Showing /srv/apps/curate_uc/vendor/bundle/ruby/2.1.0/bundler/gems/browse-everything-03442808c604/app/views/browse_everything/_files.html.erb where line #17 raised:
undefined method `item' for nil:NilClass
```

**Comment by scherztc** [comment]
The kaltura/base branch is ready and the bamboo variables are set.  This PR is ready to merge.

**Pull request merged**
