### PR TITLE
Updates facets 

### LINKED ISSUE #903: Update facets
We have made some changes to facets, for example, merging spatial and temporal subjects, and adding some new facets (like college and department).

Analyze and reimplement these changes for Sufia.

### PR DESCRIPTION
**Pull request by scherztc**
Fixes #903 

Present short summary (50 characters or less)

Updates facets to reflect Scholar 2.x
Modifies work indexers to allow date_created to be a facet.
Modifies attributes show to link to correctly faceted date_created.

### CODE REVIEW

**Comment by newmanld** [comment]
It appears that this may remove Department as a facet.  That is not desirable.  But to be consistent with Scholar 2.x functionality, Department should be a 'pivot' facet and display after the College facet is selected.  Think that @vanmiljf worked on this solution in Scholar 2.x.  If pivot facet is out of scope, Department facet should remain at top level with other facets.

**Comment by newmanld** [comment]
Another change to make facets in Scholar 3.x match 2.x - change label of 'numeric sort' to 'frequency sort'.  See https://github.com/uclibs/scholar_uc/issues/786

**Comment by newmanld** [comment]
Looks like we are removing Contributor as a facet - which I think is correct. Per metadata profile https://docs.google.com/spreadsheets/d/1biO5sm4WVK9p01jCFDzNqTQ1mF_33MEHbpCjIVaOU3M/edit?usp=sharing, is it correct that Contributor (not the same as submitter/owner ) should not be a descriptive field on works or collections?

**Comment by scherztc** [comment]
Ready for review.  

I was able to get the College and Department facet to pivot correctly.
Adjusted label to frequency sort.

**Pull request merged**
