### PR TITLE
[WIP] Reinstate share tab

### LINKED ISSUE #1243: Discuss re-enabling the share tab for works
Before Sufia 7.3.0 final was released, a change was made that hides the work share tab by default and only shows it under the right conditions within the mediated workflow.  See https://github.com/projecthydra/sufia/issues/3134

I think we always want the share tab to show in Scholar.  We can either hard code it to show or make sure the workflow allows it.  Hard coding is probably the better option for us since workflows aren't always loaded properly for us in our local environments or sandboxes.

To re-enable the tab we just change https://github.com/uclibs/scholar_uc/blob/develop/app/views/curation_concerns/base/_guts4form.html.erb#L8 
from 
`<% tabs ||= %w[metadata doi files relationships] # default tab order %>`
to
`<% tabs ||= %w[metadata doi files relationships share] # default tab order %>`

Thoughts?

### PR DESCRIPTION
**Pull request by crowesn**
Fixes #1243 

Changes proposed in this pull request:
* Reinstate share tab
* Add feature spec to check for tabs in form

### CODE REVIEW

**Comment by hortongn** [comment]
@crowesn I neglected to mention that if we're going to use the hard coded share tab we also need to remove the code for the hidden share tab here https://github.com/uclibs/scholar_uc/blob/develop/app/views/curation_concerns/base/_guts4form.html.erb#L26-L31

That's why the specs are failing.  There are now two share tabs with one of them hidden.  The lines for the hidden tab were added when we updated our app to work with 7.3.0.

**Comment by scherztc** [comment]
Check this : https://github.com/uclibs/scholar_uc/blob/develop/config/workflows/default_workflow.json#L7

**Comment by crowesn** [comment]
Looking at achieving this functionality with custom workflow.

**Comment by hortongn** [comment]
Closing via https://github.com/uclibs/scholar_uc/issues/1311#issuecomment-296737502

**Pull request closed without merging**
