### PR TITLE
Changes to set default fields for query search

### PR DESCRIPTION
**Pull request by jamesvanmil**

### CODE REVIEW

**Comment by jamesvanmil** [comment]
@newmanld please take a look at the config/search_config.yml for a list of fields I've added.

**Comment by scherztc** [comment]
James,  I did see this on another spec test:

after(:all) do
 @katie.destroy
 @alvin.destroy
 @john.destroy

https://github.com/uclibs/curate_fork/blob/da999f44e59127a621cbdef929da4186d66dd87c/spec/controllers/curate/people_controller_spec.rb.

Take a look and let me know if this let/destroy approach might work.

**Comment by jamesvanmil** [comment]
That seems to totally take care of the issue. I'm updating the branch.

**Comment by hortongn** [comment]
:+1: This works as advertised in my local environment.  All tests pass for me.

**Pull request merged**
