### PR TITLE
Feature/#155a extend keyword

### PR DESCRIPTION
**Pull request by lisa3711**
added keywords

### CODE REVIEW

**Comment by hortongn** [comment]
@lisa3711 On line #4 of config/search_config.yml you need to intent `rows: 10` two spaces to the right.  YML files are very sensitive to indentation.  Somehow that row lost a couple of spaces when the file was edited.

**Comment by lisa3711** [comment]
Hmnn--- ok, thanks!

**Comment by lisa3711** [comment]
Glen- had trouble getting local environment to sync correctly with git to push changes up. So, i edited the file directly and made a new commit. Let me know if this is not ok!

**Comment by hortongn** [comment]
Verified all of the new fields are searchable.  Since the Gemfile needs to be updated to make use of the Curate piece of this PR, I'll do that, squash everything, and merge.  Good job!

**Comment by lisa3711** [comment]
Thanks!

**Pull request merged**
