### PR TITLE
add styled file upload to the app

### PR DESCRIPTION
**Pull request by crowesn**
requires merge of https://github.com/uclibs/curate_fork/pull/93

### CODE REVIEW

**Comment by crowesn** [comment]
Travis failed because the new partial for file upload is not yet included in curate develop branch.

**Comment by hortongn** [comment]
I've updated the app on Larry to include this part of the code.  So uploading profile pics uses the new button.  Looks good to me.  If people can test on http://larry.libraries.uc.edu:3001 and give a couple of :+1:, we can get these PRs merged. @newmanld @scherztc @jamesvanmil @13miciunasl

**Comment by jamesvanmil** [comment]
Uploaded images to profiles and collections. +1

**Comment by newmanld** [comment]
Is the fix depositor editor protection (James’ PR) also in this branch on Larry?  Any other merged PRs that we should also test?

**Comment by hortongn** [comment]
@newmanld Yes, James' PR is included on Larry.  It also includes Lukas' fix for #542

**Pull request merged**
