### PR TITLE
Add college and department fields to works

### LINKED ISSUE #895: Add College and Department metadata
If feasible, best to pursue with nested metadata.

Complete implementation depends on addition of Shibboleth authentication and associated user uc department in the account information.

Related https://github.com/uclibs/scholar_uc/issues/787

### PR DESCRIPTION
**Pull request by hortongn**
Fixes #895 

Adds college and department fields to works.  Everything works just as it does in Scholar 2.x including special cases for ETDs and Student Works.

### CODE REVIEW

**Comment by hortongn** [comment]
Ready for review

**Comment by crowesn** [comment]
```
ActionView::Template::Error (undefined local variable or method `ucdepartment' for #<User:0x007faf5c42ceb8>
Did you mean?  department
               department?
               department=):
    1: <%= f.input :college,
    2:       collection: sorted_college_list_for_works,
    3:       selected: (curation_concern.college || user_college),
    4:       input_html: { class: 'college' } %>
  app/models/user.rb:53:in `college'
  app/helpers/sufia_helper.rb:47:in `user_college'
  app/views/records/edit_fields/_college.html.erb:3:in `_app_views_records_edit_fields__college_html_erb__3860225345935267843_70195716642720'
  app/views/curation_concerns/base/_guts4form.html.erb:43:in `block in _app_views_curation_concerns_base__guts_form_html_erb___2935028922201117702_70195791416260'
  app/views/curation_concerns/base/_guts4form.html.erb:35:in `each'
  app/views/curation_concerns/base/_guts4form.html.erb:35:in `each_with_index'
  app/views/curation_concerns/base/_guts4form.html.erb:35:in `_app_views_curation_concerns_base__guts_form_html_erb___2935028922201117702_70195791416260'


  Rendered /Users/crowesn/.rvm/gems/ruby-2.3.3@scholar/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_source.erb (10.0ms)
  Rendered /Users/crowesn/.rvm/gems/ruby-2.3.3@scholar/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (3.3ms)
  Rendered /Users/crowesn/.rvm/gems/ruby-2.3.3@scholar/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.7ms)
  Rendered /Users/crowesn/.rvm/gems/ruby-2.3.3@scholar/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/template_error.html.erb within rescues/layout (59.1ms)
  Rendered /Users/crowesn/.rvm/gems/ruby-2.3.3@scholar/gems/web-console-2.3.0/lib/web_console/templates/_markup.html.erb (0.6ms)
  Rendered /Users/crowesn/.rvm/gems/ruby-2.3.3@scholar/gems/web-console-2.3.0/lib/web_console/templates/_inner_console_markup.html.erb within layouts/inlined_string (0.5ms)
  Rendered /Users/crowesn/.rvm/gems/ruby-2.3.3@scholar/gems/web-console-2.3.0/lib/web_console/templates/_prompt_box_markup.html.erb within layouts/inlined_string (0.4ms)
  Rendered /Users/crowesn/.rvm/gems/ruby-2.3.3@scholar/gems/web-console-2.3.0/lib/web_console/templates/style.css.erb within layouts/inlined_string (0.6ms)
  Rendered /Users/crowesn/.rvm/gems/ruby-2.3.3@scholar/gems/web-console-2.3.0/lib/web_console/templates/console.js.erb within layouts/javascript (46.6ms)
  Rendered /Users/crowesn/.rvm/gems/ruby-2.3.3@scholar/gems/web-console-2.3.0/lib/web_console/templates/main.js.erb within layouts/javascript (0.4ms)
  Rendered /Users/crowesn/.rvm/gems/ruby-2.3.3@scholar/gems/web-console-2.3.0/lib/web_console/templates/error_page.js.erb within layouts/javascript (0.5ms)
  Rendered /Users/crowesn/.rvm/gems/ruby-2.3.3@scholar/gems/web-console-2.3.0/lib/web_console/templates/index.html.erb (101.5ms)
```

**Comment by hortongn** [comment]
@crowesn That sounds like you need to do a db:migrate.  This PR has a migration that adds a ucdepartment column to the user model.

**Comment by crowesn** [comment]
👍

**Pull request merged**
