### PR TITLE
[WIP]Configure UV and RIIF for Sufia.

### LINKED ISSUE #898: IIIF display of images
When the file is an image type, display the image with OpenSeadragon.

This will require a redesign of the work show page to make room for the viewer.

### PR DESCRIPTION
**Pull request by scherztc**
Fixes #898 

Summary:

Cherry picks Hyku use of a Universal Image Viewer and RIIIF to give the works a zoom and pan option for attached image files.

### CODE REVIEW

**Comment by hortongn** [comment]
@scherztc I think because the multiple work types PR got merged in earlier today, you need to rebase your iiif branch.  There's a conflict in GenericWorksController.

**Comment by 13miciunasl** [comment]
Is this not pinned to a Sufia release where it got rid of the issue where you couldn't edit your own work and then it removes your access to said work? I got the same error, and I'm wondering if you re-introduced something

**Comment by 13miciunasl** [comment]
Trying to save a work with a .jp2 file attached results in this error:

`identify /var/folders/9v/_dfn9t5j49xglmwybfzcg5t80000gr/T/mini_magick20170203-13807-17y78yy.jp2` failed with error: 
identify: no decode delegate for this image format `JP2' @ error/constitute.c/ReadImage/504.

**Comment by 13miciunasl** [comment]
Using the edit action on a file:

NoMethodError in CurationConcerns::FileSets#edit 
undefined method `manifest_path' for #<ActionDispatch::Routing::RoutesProxy:0x007fc9cbeac328>

**Comment by 13miciunasl** [comment]
Clicking on a file title will result in this error:

 NoMethodError in CurationConcerns::FileSets#show 
undefined method `manifest_curation_concerns_file_set_path' for #<ActionDispatch::Routing::RoutesProxy:0x007fc9cac30c08>
Did you mean?  manifest_curation_concerns_image_path

**Comment by scherztc** [comment]
See rebased PR: https://github.com/uclibs/scholar_uc/pull/1234

**Pull request closed without merging**
