### PR TITLE
add contextual help for attaching files to work

### LINKED ISSUE #1452: Need contextual help for Attaching a file to new works
### Descriptive summary

Add some contextual to encourage adding files on the (single work) input forms.

### PR DESCRIPTION
**Pull request by lawhorkl**
Fixes #1452 

After segmenting the text as agreed yesterday, I found that a tad of javascript was required to properly transition from metadata to the files tab.

Also, includes a new override of the `_form_files.html.erb` partial.

### CODE REVIEW

**Comment by crowesn** [comment]
👍 

Screencaps added for @newmanld review.

screen shot 2017-08-02 at 11 17 15 am
---
screen shot 2017-08-02 at 11 17 22 am

**Comment by hortongn** [comment]
@lawhorkl Good job.  There's a small typo in the Files tab text: "sumbitting"

Also, on the Metadata tab I think it would be better to extend the hyperlink text to include "Attaching a file" instead of just "file".  If we want our site to be more accessible, we should make sure our link text does a good job describing the action. 

@newmanld Do you see the need for any more changes before we merge?

**Comment by newmanld** [comment]
@crowesn has given P.O.s until Monday 8/7 to comment.

I’m thinking that the sentence with the typo may not be necessary  at all.  (“To attach a file <…> before submitting your work.”)  Users are already reminded about required metadata fields by the check box in the floating pane.

**Comment by lawhorkl** [comment]
The line has been removed.

**Comment by crowesn** [comment]
```
Hi all,
 
On the “Add Local Files” tab, I’m not sure if all of that explanatory text is necessary.  It seems like a lot of info at a point in the process where a user likely knows these things. 
 
I suggest removing these sentences for simplicity:
Scholar@uc exists to share and preserve the intellectual output of UC scholars and researchers.  Scholar@uc may not preserve your work without digital files. 
 
Hope this opinion is helpful.  
 
Ted
```

**Comment by lawhorkl** [comment]
Awaiting any direction as to what to do. Unsure of whether to change it again or leave as is.

**Comment by crowesn** [comment]
@lawhorkl Please make changes as per Ted’s message.

**Comment by newmanld** [comment]
With the additional removal of the sentence I recommended, we will have admirably shorter text.  So I’m suggesting adding ‘on the Metadata tab’ after ‘External Link field’, as I think we have room for that small bit of extra clarity:

Attaching a file is highly recommended but not required.  Pre-prints are encouraged if a publisher does not permit sharing a published article. Use the External Link field on the Metadata tab to point to related content found outside of Scholar@UC.

**Comment by lawhorkl** [comment]
@crowesn @newmanld changes updated.

**Pull request merged**
