### PR TITLE
Pins sufia to version 7.2

### LINKED ISSUE #949: Update to Sufia 7.2

### PR DESCRIPTION
**Pull request by scherztc**
Closed #949

### CODE REVIEW

**Comment by crowesn** [comment]
Layout setting is [here](https://github.com/uclibs/scholar_uc/blob/release-3/initial_commit/app/controllers/application_controller.rb#L14)

This should be ready to merge.

👍

**Comment by lawhorkl** [comment]
Running into error about cannot find table `sufia_features`

This needs migration https://github.com/projecthydra/sufia/blob/master/db/migrate/20160415212015_create_features.rb 
After this is added should be good to go.

**Comment by crowesn** [comment]
👍

**Comment by lawhorkl** [comment]
👍 

Went through the app and was able to perform all the basic CRUD. No display issues found.

Merging.

**Pull request merged**
