### PR TITLE
Updates UV to use pul_uv_rails.

### LINKED ISSUE #1867: Download option in Image Viewer doesnt work
### Descriptive summary

In the current version of Scholar@UC based on Hyrax 1.x the is a download button in the image viewer.  It doesn't worked.  This may be improved or resolved in Hyrax 2.x where the Image Viewer is incorporated into the release.  

### Expected behavior
Download button gives options for size, and then allows the user to export an image.

### Actual behavior
A message appears that says "No download options are available."

### Steps to reproduce the behavior

Go to a work with an image, such as https://scholar.uc.edu/show/bc386t80f
Select the download button in the lower left-hand corner of the image viewer.

### Related work
Public files can be downloaded from the file listing further down on the work show page.  An adequate solution may be to suppress this button.

### LINKED ISSUE #1880: Embed Option in Image Viewer doesn't work.
### Descriptive summary

When viewing an image in Scholar@UC that displays in the Universal Viewer, an option appears bottom left to copy embed code.  For this work: https://scholar.uc.edu/show/8g84mm26k, the Embed code looks like this:  
`<div class="uv" data-locale="en-GB:English (GB),cy-GB:Cymraeg" data-config="" data-uri="/concern/images/8g84mm26k/manifest?locale=en" data-collectionindex="0" data-manifestindex="0" data-sequenceindex="0" data-canvasindex="0" data-zoom="-0.1237,-0.0368,1.2475,0.7367" data-rotation="0" style="width:780px; height:400px; background-color: #000"></div>`
`<script type="text/javascript" id="embedUV" src="https://scholar.uc.edu/bower_includes/universalviewer/dist/uv-1.7.11/lib/embed.js"></script><script type="text/javascript">/* wordpress fix */</script>`

I've created a test web page and the window for the universal viewer appears, but not the image.  The javascript console indicates that it cannot find the file named jquery.min.js, and it appears to be looking in my local environment for file://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js.

### Expected behavior
Using the provided embed code on a webpage external to Scholar@UC will result in a functioning universal viewer with the image.

### Actual behavior
A blank universal viewer window appears.

### Steps to reproduce the behavior

1. Locate a public image work with a public attached file.
1. Click on the embed symbol in the lower left.

### Related work
#1867 

Suggest determining if this appears to be functioning in Hyrax 2.1 (nurax.curationexperts.com), but also looking for an UV configuration steps we might have missed, any whether any straightforward fix to our Scholar environment using Hyrax 1.x is also possible.

### PR DESCRIPTION
**Pull request by scherztc**
Fixes #1867 
Fixes #1880 

Present short summary (50 characters or less)

Fixes the download and embed option in the Universal Viewer by upgrading to version 2.0.1.

Changes proposed in this pull request:
* Removes the local implementation of Universal Viewer from our application.
* Includes the pulibrary/pul_uv_rails gem for managing Universal Viewer versions. (1.7 -> 2.0.1)
* Inserts UV into application views.

Related Links:

https://github.com/samvera/hyrax/commit/e1f84ede09f63d730cae2fc9e2940be7cc6572cd

### CODE REVIEW

**Comment by hortongn** [comment]
@scherztc When I tested the UV embed option in my local environment, it is still broken for me.  All I get is a black box on the web page where I inserted the embedded code.

The javascript console still gives a `ERR_FILE_NOT_FOUND` for jquery,min.js like Linda reported in #1880.  I think the problem is it's looking for `file://cdnjs.cloudflare.com/ajax/libs/jquery/1.10.2/jquery.min.js` which is using `file://` instead of `http://`.  I think it's trying to use `file://` because I'm embedding it into a local HTML file on my machine.  

If I embedded the code into a page that uses `http://` it works properly.  So I guess the question is "Do we care if the embedded code only works "real" web pages running under `http://`?  Is it important that it also work in a local file like `file://localhost:3000/test.html`?

Good question for @newmanld ?

**Comment by newmanld** [comment]
I think that we don't care if the code only breaks on a local file,  but that we should emulate real world testing to make sure it does work in a webserver environment outside of our own own dev or production environments.  @scherztc let me know if you want to use https://digital.libraries.uc.edu to host a web page with our embed code.

**Comment by scherztc** [comment]
@hortongn :  I originally included the presenter logic in case we wanted to do your views different, but decided to keep it our current views.

**Comment by hortongn** [comment]
I am 👍 on this as long as the download and embed options work when we test it on scholar-dev.

**Pull request merged**
