### PR TITLE
Update UC logo in title bar

### LINKED ISSUE #1130: Replace UC logo with new logo
### Descriptive summary

UC branding has released the new logo and it is time to use it in Scholar 2.x

Current image: https://scholar.uc.edu/assets/uc/UC_logo-05d56945cbf77e6885dfae4682214509.png
Does this translate to here?:
https://github.com/uclibs/scholar_uc/blob/2.x-stable/app/assets/images/uc/UC_logo.png
or
https://github.com/uclibs/scholar_uc/blob/master/app/assets/images/uc/UC_logo.png

New UC logo can be found here: 
http://www.uc.edu/ucomm/brand.html
And specifically use the zip file downloaded from here: http://www.uc.edu/content/dam/uc/ucomm/branding/UC_Logo_Primary_EPS.zip

Old logo image appears to have the dimensions of 151 px width x 66 px high.  Attached is an image of the new logo at 66 px high - but to keep it in proportion it is slightly narrower at 147 px.
uc_id_primaryblackred

Keep same amount of white space around the image.

### PR DESCRIPTION
**Pull request by 13miciunasl**
Fixes #1130

Replaces old UC logo with the new one

### CODE REVIEW

**Comment by hortongn** [comment]
@13miciunasl Can you add a screenshot to this PR so Linda can easily see it?

**Comment by crowesn** [comment]
👍 

screen shot 2017-02-09 at 10 33 30 am

**Comment by hortongn** [comment]
👍  Looks good to me.  

@newmanld Does the screenshot above look acceptable to you?

**Comment by newmanld** [comment]
Looks good to me.  Let’s double check that it still disappears on mobile.

**Comment by hortongn** [comment]
@newmanld It does.  I pulled it up in my own environment and checked.  So I'll merge.

**Pull request merged**
