### PR TITLE
Add ORCID integration

### LINKED ISSUE #854: Add ORCID integration

### PR DESCRIPTION
**Pull request by crowesn**
Fixes #854

Add ORCID integration for Scholar 3.x. User can create or add existing ORCID id to profile. This commit includes a CallbacksController which can also contain logic for shibboleth authentication when we cross that bridge.

Changes proposed in this pull request:
* Add ORCID api integration

### CODE REVIEW

**Comment by crowesn** [comment]
I'll add a feature spec for the ORCID partial display.

**Comment by 13miciunasl** [comment]
+1

**Comment by hortongn** [comment]
@crowesn one of the PRs we merged today caused a conflict in your branch.  Please rebase and push up again.

**Comment by crowesn** [comment]
@hortongn this is failing because of a coverage percentage decrease. I'd be happy to chat about how to test but I *think* it's bogus.

**Comment by hortongn** [comment]
@crowesn I looked it over again and I maintain that there is untested code here that would be risky to merge in as-is.  

As it is now, the CallbacksController could be modified or even removed completely and none of the tests would break.  We will eventually add Shibboleth to this controller.  So it's important to know that the orcid method doesn't break.  There needs to be at least one test that does a `get orcid` and verifies the proper response.  You can see an example of how I mocked the omni hash and tested the response at https://github.com/uclibs/scholar_uc/blob/2.x-stable/spec/controllers/callbacks_controller_spec.rb#L4-L35

For the user/user_info view partial, it's important to have a test that at least checks to make sure the ORCID status "widget" is present.  Without a test, If a developer ever removed this partial thinking that the override was not needed anymore, it would silently disappear until we noticed it was gone.

We can chat more about it if you like.

**Comment by crowesn** [comment]
This PR has a partial that I'm going to editing in my next issue. Would be nice to get it merged asap.

**Comment by hortongn** [comment]
@crowesn Good job.  merging

**Pull request merged**
