### PR TITLE
Swap work for generic work type

### LINKED ISSUE #982: Replace Work model/structure with GenericWork
### Descriptive summary

Change Work model name to GenericWork.

1. `rails destroy sufia:work Work`
1. `rails generate sufia:work GenericWork`
1. Clean up specs

### Related work

Related: #979 

Size: 4

### PR DESCRIPTION
**Pull request by crowesn**
Fixes #982 

* Change work to generic_work
* Adapt CRUD work feature tests with shared_examples to accommodate multiple work types.

Relies on #1031 to fix test weirdness.

### CODE REVIEW

**Comment by crowesn** [comment]
The virus_checker feature test is really iffy on my local env.

**Comment by crowesn** [comment]
@uclibs/developers Can this be the next PR that gets merged? I have to fix it every time something else is merged.

**Comment by scherztc** [comment]
@jamesvanmil.  Let's talk about this with the three of us together.

**Comment by scherztc** [comment]
There are two test failing in my local environment (rake ci).  They are both related to the anti-virus rebase.  

Finished in 3 minutes 25.2 seconds (files took 48.48 seconds to load)
131 examples, 2 failures, 14 pending

Failed examples:

rspec ./spec/features/virus_scan_spec.rb[1:1:1:1] # Adding an infected file to and existing work behaves like infected submission drops the file(s) before saving the work and alerts the user

rspec ./spec/features/virus_scan_spec.rb[1:2:1:1] # Adding an infected file to a new work behaves like infected submission drops the file(s) before saving the work and alerts the user

Can someone else run the test locally and let me know if you are seeing the same thing?

**Comment by crowesn** [comment]
I was getting intermittent failures for those on my local.

**Comment by scherztc** [comment]
I can try running them in isolation.  I think it has to do with the re-direct path in the controller.  https://github.com/uclibs/scholar_uc/blob/0f60597610d294d28bbbee70ec9deb3ffe5c32e9/app/controllers/curation_concerns/generic_works_controller.rb

**Comment by hortongn** [comment]
@crowesn I just tried it and can verify that the virus specs pass on the `develop` branch but fail in your topic branch.  I'm taking a quick look to see if there's an obvious tweak needed in the virus spec tests.

**Comment by hortongn** [comment]
@crowesn Does the problem exist with more than just the virus scan specs?  I noticed that you have have a `skip "This was failing intermittently"` in your create work feature test here: https://github.com/uclibs/scholar_uc/blob/0f60597610d294d28bbbee70ec9deb3ffe5c32e9/spec/features/create_generic_work_spec.rb#L22

**Comment by crowesn** [comment]
Yes, it does. In addition to failures associated with that skip (which came over from the sufia tests)  capybara seems to be generally unreliable for a lot of these tests.

**Comment by scherztc** [comment]
@crowesn :  Is this ready for review again?

**Comment by crowesn** [comment]
Yep!

**Comment by scherztc** [comment]
screen shot 2016-12-14 at 12 28 00 pm

@crowesn :  I saw this in the facets when I created a new work.  Would we expect this to say GenericWork?

**Comment by scherztc** [comment]
Check human_readable_type

**Comment by scherztc** [comment]
Now we get this and a failure on rspec ./spec/features/end_to_end_spec.rb:89 # end to end behavior: the user can view the new work form.  Fixes the spec isn't a problem it is more about the menu for multiple work types.  

screen shot 2016-12-14 at 12 28 00 pm

I am not sure what we want here.  Let's have a conversation about this tomorrow.

**Comment by scherztc** [comment]
Let's keep an eye on this:  https://github.com/projecthydra-labs/hyku/issues/496#issuecomment-267163243

**Comment by crowesn** [comment]
Here are some screen grabs from sufia/master with multiple work types. Here I have two generated work types: Generic Work, and Image. Note that top-level control labels revert to 'create work' in 7.3.0. I *think* these have been labeled _Work_ to accommodate multiple work types.

I think this should address your concerns about labeling behavior in 7.3?

screen shot 2016-12-16 at 9 38 51 am
screen shot 2016-12-16 at 9 38 59 am
screen shot 2016-12-16 at 9 39 54 am

**Pull request merged**
