### PR TITLE
Add student work help page and associated help pages

### LINKED ISSUE #1126: New Help Page - Student Works
### Descriptive summary

As approved by DRTF with content from Content Working group, add a new page to the Help menu, entitled: Student Works.  This page in turn will link to two other new pages: Guidelines for Faculty and Instructions for Students.  Text of page below:

Scholar@UC was developed to store and share the scholarly output and creative works of UC faculty (current and emeritus), staff, and students. Works that are deposited in Scholar@UC should support the mission of the University of Cincinnati. Students should work with a faculty member to share scholarly output and creative works, such a capstone projects. **All official theses and dissertations must be submitted directly to the Graduate School and not Scholar@UC.**

There are two main workflows for submitting student works to Scholar@UC: Self-Submission and Indirect Submission.

Self-Submission of Student Works is the preferred method of submitting student works.
•	Guidelines for Faculty  (link to new page)
•	Instructions for Students (link to new page)

Indirect submissions are when students submit first to a system other than Scholar@UC, such as [Canopy](https://canopy.uc.edu).   Direct, self-submission is preferred as it allows students, in Scholar@UC, to agree to the non-exclusive distribution license and to select their own licensing terms for reuse (Creative Commons).  In some cases indirect submissions are necessary, and in that case please contact [scholar@uc.edu](mailto:scholar@uc.edu) for additional help.

### PR DESCRIPTION
**Pull request by 13miciunasl**
Fixes #1126 #1127 #1128 #1047 

Adds 3 new help pages revolving around student works

### CODE REVIEW

**Comment by newmanld** [comment]
Screenshots?

**Comment by newmanld** [comment]
Also -  on #1126 per comment, I thought we were going to try to remove the file format advice at the end of page, and incorporate this advice instead into the File Format Advice help page.  See also #1048.  Modify sentence at the beginning of step 5 accordingly.

**Comment by 13miciunasl** [comment]
screen shot 2017-02-10 at 11 13 45 am
screen shot 2017-02-10 at 11 13 59 am
screen shot 2017-02-10 at 11 14 15 am
screen shot 2017-02-10 at 11 15 16 am
screen shot 2017-02-10 at 11 15 30 am
screen shot 2017-02-10 at 11 15 38 am
screen shot 2017-02-10 at 11 15 46 am

And for the File Format Advice page

screen shot 2017-02-10 at 11 16 02 am

**Comment by 13miciunasl** [comment]
@newmanld

**Comment by newmanld** [comment]
On File Format Advice page please move new Accessibility paragraph to be  between Access Files and Preservation Files areas.  In other words, above Preservation Files.  Please provide new screenshot, if possible for entire page.  Other changes in this PR all look good - although reviewing using a browser pointing to localhost or sandbox would be a good double check.

**Comment by 13miciunasl** [comment]
Here are the updated screenshots
screen shot 2017-02-13 at 9 21 32 am
screen shot 2017-02-13 at 9 21 49 am

**Comment by newmanld** [comment]
On the file format advice page, after "The file format you will use will affect it's preservability.  some specific guidance is offered below." -- Please remove the additional clause that says "; you will find additional details on our File Format Advice page."  This is now self-referencing.

Also please remove the bullet point for UMich Bentley.  It appears that they have taken down this page. (http://bentley.umich.edu/uarphome/bestprac/pdfafaqs.php)

**Comment by newmanld** [comment]
On the Student Instructions page, point 5, please change this to say:
Please see the [File Format Advice](https://scholar.uc.edu/format_advice_request) page for information about the accessible, usable and preservable formats. Add a file to your work by:

**Comment by 13miciunasl** [comment]
Let me know if I missed anything

screen shot 2017-02-13 at 1 30 56 pm
screen shot 2017-02-13 at 1 31 15 pm

**Comment by newmanld** [comment]
See two new comments added to github issue #1127

**Comment by newmanld** [comment]
Looking good to me.  Maybe double check that mobile view is ok, then merge PR?

**Comment by 13miciunasl** [comment]
@newmanld The pages look very good on mobile. All set to merge

**Comment by 13miciunasl** [comment]
@newmanld The accessibility page in the help drop-down has been added. You can merge this now

**Pull request merged**
