### PR TITLE
Creates ClassifyConcerns for displaying of work landing page.

### LINKED ISSUE #1420: Hyrax:  Port over ClassifyConcerns model from CurationConcerns
### Descriptive summary

This code in CurationConcerns needs to be moved into our application to allow the use of the work type landing page instead of the modal.

### PR DESCRIPTION
**Pull request by scherztc**
Fixes #1420 

Creates new model, controller, and views in our application for ClassifyConcerns.  
Adjust ability.rb for new application model.

### CODE REVIEW

**Comment by hortongn** [comment]
@scherztc If you're pulling the ClassifyConcernsController into the app, you should also bring in the controller spec from https://github.com/samvera/curation_concerns/blob/v1.7.7/spec/controllers/curation_concerns/classify_concerns_controller_spec.rb

That will help keep Coveralls happy.

**Comment by jamesvanmil** [comment]
@scherztc can you rebase against the hyrax branch to get the rubocop fixes?

**Comment by jamesvanmil** [comment]
Also, after reviewing the remaining failures, this one caught my eye - I'm digging in a little deeper, but wanted to get it recorded:

```ruby
  340) dashboard/_create_work_action.html.erb when we have more than one model renders the select template
       Failure/Error: <%= link_to(Hyrax::Engine.routes.url_helpers.new_classify_concern_path) do %>

       ActionView::Template::Error:
         undefined method `new_classify_concern_path' for #<Module:0x007fa17ccff6a0>
         Did you mean?  new_admin_set_path
       # ./app/views/dashboard/_create_work_action.html.erb:3:in `_app_views_dashboard__create_work_action_html_erb___3357868666742523195_70165780351560'
       # ./spec/views/dashboard/create_work_action.html.erb_spec.rb:8:in `block (2 levels) in <top (required)>'
       # ------------------
       # --- Caused by: ---
       # NoMethodError:
       #   undefined method `new_classify_concern_path' for #<Module:0x007fa17ccff6a0>
       #   Did you mean?  new_admin_set_path
       #   ./app/views/dashboard/_create_work_action.html.erb:3:in `_app_views_dashboard__create_work_action_html_erb___3357868666742523195_70165780351560'
```

**Comment by jamesvanmil** [comment]
@scherztc I think we may actually be able to get rid of this file: `app/views/dashboard/_create_work_action.html.erb` and the spec

**Pull request merged**
