### PR TITLE
fix floating footer bug and affix to bottom of browser window

### LINKED ISSUE #921: page footer should stay at bottom of page
the page footer in the UI should stay at the bottom of the page. 

i have experience in doing this sort of thing with bootstrap already, so ill go ahead and fix this up myself.

image

### PR DESCRIPTION
**Pull request by lawhorkl**
closes #921 

we should consider contributing this back to sufia

### CODE REVIEW

**Comment by crowesn** [comment]
https://github.com/projecthydra/sufia/issues/2661

**Comment by hortongn** [comment]
@lawhorkl This doesn't seem to be working for me.  See screenshot below.  The black footer still hovers near the middle of the page when there isn't much content on the screen.

index catalog scholar uc

**Comment by crowesn** [comment]
This needs to be rebased over the release-3 branch. I noticed that sufia is still pointed to master in the Gemfile.

**Comment by scherztc** [comment]
Where are we on this one?  There is a trello card for this:  https://trello.com/c/nMU1zD6F/21-as-a-user-i-want-to-have-the-page-footer-anchored-to-the-bottom-of-the-page-so-that-i-can-easily-access-global-content-navigatio

**Comment by lawhorkl** [comment]
updated and rebased this - should be fixed and good to go

**Pull request merged**
