### PR TITLE
Add content freeze message to 404 page

### LINKED ISSUE #1694: Tweak 404 template for content freeze
### Descriptive summary

We need to draft a 404 template for the temporary content freeze. 

Points to include:
1. Temporary content freeze
1. Content is view only
1. Affects all content including profiles

### PR DESCRIPTION
**Pull request by 13miciunasl**
Fixes #1694 
Adds text explaining the temporary content freeze to the 404 page.

### CODE REVIEW

**Comment by jayanthdeejay** [comment]
@13miciunasl My bad. 404.html is the correct place for these changes and not 500.html. For some reason, I had to update 500.html on Larry and suggested you to do so accordingly. Just pulled your changes locally and made Fedora read-only and tested it. Works like a charm. Thanks.

screen shot 2017-10-11 at 3 34 14 pm

**Comment by hortongn** [comment]
I feel like this page should have a bulleted list of the specific tasks that are not allowed during the freeze.  E.g.

```
While Scholar@UC is in view-only mode, users will not be able to
* create or edit works
* create or edit collections
* create or edit groups
* edit their profile page

Users that have never logged into Scholar@UC in the past will not be able to log in while the site is in view-only mode.
```

**Comment by crowesn** [comment]
@13miciunasl screenshot?

**Comment by 13miciunasl** [comment]
I actually haven't been able to get scholar 2 running, so I've been going off hope mostly.

**Comment by jayanthdeejay** [comment]
I have a working Scholar 2 locally and updated 404.html with @13miciunasl code and here is the screenshot.

screen shot 2017-10-18 at 2 52 09 pm

**Comment by crowesn** [comment]
How about something like this for more emphasis on the freeze?

**Comment by hortongn** [comment]
👍 I agree with making the freeze message easier to notice.

**Comment by crowesn** [comment]
Freeze message in alert block:

screen shot 2017-10-19 at 11 35 32 am

**Pull request merged**
