### PR TITLE
Hyrax 1.0.5 upgrade

### LINKED ISSUE #1715: Hyrax 1.0.5
### Descriptive summary

Hyrax has minted a [1.0.5 release](https://github.com/samvera/hyrax/releases/tag/v1.0.5)
Research and upgrade.

### PR DESCRIPTION
**Pull request by jayanthdeejay**
Fixes #1715  ; 

Hyrax gem upgrade from 1.0.4 to 1.0.5

Changes proposed in this pull request:
* Hyrax Gem upgrade

Test suite was successful locally with no errors.

### CODE REVIEW

**Comment by crowesn** [comment]
@jayanthdeejay Can we get some notes about the nature of the changes in the release? Does this collide with any of our overrides?

**Comment by jayanthdeejay** [comment]
Community seems have invested some time on BrowseEverything issue without much progress in that direction. Following is the release notes from Samvera Hyrax Github page

"Hyrax 1.0.5 is a bug fix release that validates local file ingestions (i.e., from BrowseEverything) against a whitelist of directories." --[Mike Giarlo](https://github.com/samvera/hyrax/releases)

Looked at the Hyrax gem and could find no major features/security fixes in this release. 

Overrides: None.

```shell
diff --brief -Nr hyrax-1.0.4 hyrax-1.0.5
Files hyrax-1.0.4/README.md and hyrax-1.0.5/README.md differ
Files hyrax-1.0.4/app/actors/hyrax/create_with_remote_files_actor.rb and hyrax-1.0.5/app/actors/hyrax/create_with_remote_files_actor.rb differ
Files hyrax-1.0.4/lib/generators/hyrax/templates/config/hyrax.rb and hyrax-1.0.5/lib/generators/hyrax/templates/config/hyrax.rb differ
Files hyrax-1.0.4/lib/hyrax/configuration.rb and hyrax-1.0.5/lib/hyrax/configuration.rb differ
Files hyrax-1.0.4/lib/hyrax/version.rb and hyrax-1.0.5/lib/hyrax/version.rb differ
Files hyrax-1.0.4/spec/actors/hyrax/create_with_remote_files_actor_spec.rb and hyrax-1.0.5/spec/actors/hyrax/create_with_remote_files_actor_spec.rb differ
Files hyrax-1.0.4/spec/jobs/import_url_job_spec.rb and hyrax-1.0.5/spec/jobs/import_url_job_spec.rb differ
Files hyrax-1.0.4/spec/lib/hyrax/configuration_spec.rb and hyrax-1.0.5/spec/lib/hyrax/configuration_spec.rb differ
Files hyrax-1.0.4/template.rb and hyrax-1.0.5/template.rb differ
```

**Comment by hortongn** [comment]
@jayanthdeejay This looks good, but we should add the following lines near the end of our `config/initializers/hyrax.rb.sample` and `config/initializers/hyrax.rb.bamboo` in case we ever need to use this new config option in the future.  You can add it to this PR and just leave them commented out for now.

https://github.com/samvera/hyrax/blob/8e96197d43e5a70fe94fee8308251654b6bc24e6/lib/generators/hyrax/templates/config/hyrax.rb#L190-L204

**Comment by jayanthdeejay** [comment]
@hortongn Done.

**Pull request merged**
